# Base configs
baseurl: "https://kacperrajchel.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "./images/fulls"
image_thumbs_loc: "./images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Kacper Rajchel"
subtitle: "Yep"
author: "Kacper Rajchel"
header:
 title: "Photography"
 subtitle: "by Kacper Rajchel"
footer:
 name: "Greetings"
 bio: "ML engineer with a background in the arts."
 github: "Just <a href=\"https://github.com/Crytoma/photography\">fork me on github</a>"
web_design: "KR"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  #twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/kakushidori"
  #dribbble: "https://dribbble.com/"
  #linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/Crytoma"
